model = "gpt-5.5"
model_reasoning_effort = "xhigh"
notify = [ "C:\\Users\\HUAWEI\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\1b23c930bdf84ed6\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]
model_provider = "openai"
service_tier = "priority"
[mcp_servers]

[mcp_servers.consensus]
url = "https://mcp.consensus.app/mcp"

[mcp_servers.node_repl]
args = []
command = 'C:\Users\HUAWEI\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_repl.exe'
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\HUAWEI\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\HUAWEI\AppData\Local\OpenAI\Codex\runtimes\cua_node\1b23c930bdf84ed6\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\HUAWEI\.codex'
CODEX_HOME = 'C:\Users\HUAWEI\.codex'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "566be6ef352eb3de899adc56a9cd7b5e46c8f65b00e56b5630dd7a580e10cbea,59e7bb81812ddd5f102e1d580335166e552c91686b5726218a985b59b4f89ca1"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.42026"
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-44e1e199-84eb-40f1-8cbe-7fe0ff6f5e87'
CODEX_CLI_PATH = 'C:\Users\HUAWEI\AppData\Local\OpenAI\Codex\bin\aec6b7c6fcdfb66a\codex.exe'

[windows]
sandbox = "elevated"

[plugins."academic-research-skills@local"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[projects.'d:\aaa\aaaprojects\cloud-sever']
trust_level = "trusted"

[projects.'d:\aaa\aaacourse\tasks\the philosophical foundations of human politics']
trust_level = "trusted"

[projects.'d:\aaa\aaaprojects\qa']
trust_level = "trusted"

[projects.'d:\aaa\aaaprojects\undergoing\test_ai_data']
trust_level = "trusted"

[projects.'d:\aaa\aaaprojects\undergoing\test_ai_data\nanobanana_pet-ct']
trust_level = "trusted"

[projects.'d:\aaa\aaaprojects\automation']
trust_level = "trusted"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-24T07:49:28Z"
source_type = "local"
source = '\\?\C:\Users\HUAWEI\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[marketplaces.openai-bundled]
last_updated = "2026-06-28T15:59:16Z"
source_type = "local"
source = '\\?\C:\Users\HUAWEI\.codex\.tmp\bundled-marketplaces\openai-bundled'

[desktop]
followUpQueueMode = "queue"

[features]
js_repl = false

